import { L } from "./i18n";
import type { LText } from "./types";

export type OfficialSource = { id: string; name: LText; url: string; why: LText; confirm: LText };

export const OFFICIAL_SOURCES: OfficialSource[] = [
  { id: "tamm", name: L("TAMM", "تم"), url: "https://www.tamm.abudhabi", why: L("Abu Dhabi's unified government-services platform for residents and businesses.", "منصة أبوظبي الموحدة للخدمات الحكومية للمقيمين والشركات."), confirm: L("Which government transactions apply to your situation.", "المعاملات الحكومية التي تنطبق على حالتك.") },
  { id: "adro", name: L("Abu Dhabi Residents Office", "مكتب أبوظبي للمقيمين"), url: "https://www.adro.gov.ae", why: L("Supports talent, investors and families settling in Abu Dhabi.", "يدعم المواهب والمستثمرين والعائلات للاستقرار في أبوظبي."), confirm: L("Programmes and residency pathways you may qualify for.", "البرامج ومسارات الإقامة التي قد تكون مؤهلاً لها.") },
  { id: "icp", name: L("ICP — Identity & Citizenship", "الهيئة الاتحادية للهوية والجنسية"), url: "https://icp.gov.ae", why: L("Federal authority for visas, residency and Emirates ID.", "الجهة الاتحادية للتأشيرات والإقامة والهوية الإماراتية."), confirm: L("Visa type, eligibility and required documents.", "نوع التأشيرة والأهلية والمستندات المطلوبة.") },
  { id: "uaepass", name: L("UAE PASS", "الهوية الرقمية UAE PASS"), url: "https://uaepass.ae", why: L("National digital identity used to access most government services.", "الهوية الرقمية الوطنية للوصول إلى معظم الخدمات الحكومية."), confirm: L("When you can register after receiving your Emirates ID.", "موعد التسجيل بعد استلام الهوية الإماراتية.") },
  { id: "mohre", name: L("MOHRE", "وزارة الموارد البشرية والتوطين"), url: "https://www.mohre.gov.ae", why: L("Work permits, labour contracts and employer obligations.", "تصاريح العمل وعقود العمل والتزامات صاحب العمل."), confirm: L("Work permit requirements for you or your employees.", "متطلبات تصريح العمل لك أو لموظفيك.") },
  { id: "added", name: L("ADDED — Economic Development", "دائرة التنمية الاقتصادية"), url: "https://added.gov.ae", why: L("Mainland business licensing and economic activities.", "الترخيص التجاري في البر الرئيسي والأنشطة الاقتصادية."), confirm: L("Licence type and permitted activities.", "نوع الرخصة والأنشطة المسموح بها.") },
  { id: "adgm", name: L("ADGM", "سوق أبوظبي العالمي"), url: "https://www.adgm.com", why: L("International financial centre with common-law framework.", "مركز مالي دولي بإطار القانون العام."), confirm: L("Whether an ADGM entity suits your business model.", "مدى ملاءمة كيان في سوق أبوظبي العالمي لنموذج عملك.") },
  { id: "hub71", name: L("Hub71", "هب71"), url: "https://www.hub71.com", why: L("Abu Dhabi's global tech ecosystem for startups and founders.", "منظومة أبوظبي العالمية للتكنولوجيا للشركات الناشئة والمؤسسين."), confirm: L("Programme fit, intake dates and incentive conditions.", "ملاءمة البرنامج ومواعيد القبول وشروط الحوافز.") },
  { id: "adio", name: L("ADIO — Investment Office", "مكتب أبوظبي للاستثمار"), url: "https://www.investinabudhabi.ae", why: L("Supports companies investing and expanding in Abu Dhabi.", "يدعم الشركات المستثمرة والمتوسعة في أبوظبي."), confirm: L("Sector incentives and investor support available.", "الحوافز القطاعية ودعم المستثمرين المتاح.") },
  { id: "chamber", name: L("Abu Dhabi Chamber", "غرفة أبوظبي"), url: "https://www.abudhabichamber.ae", why: L("Business community, networking and member services.", "مجتمع الأعمال والتواصل وخدمات الأعضاء."), confirm: L("Membership requirements and business councils.", "متطلبات العضوية ومجالس الأعمال.") },
  { id: "adek", name: L("ADEK — Education", "دائرة التعليم والمعرفة"), url: "https://www.adek.gov.ae", why: L("Regulates schools and publishes school information.", "تنظم المدارس وتنشر معلومات عنها."), confirm: L("School ratings, curricula and enrolment windows.", "تقييمات المدارس والمناهج ومواعيد التسجيل.") },
  { id: "doh", name: L("Department of Health", "دائرة الصحة"), url: "https://www.doh.gov.ae", why: L("Healthcare regulation and mandatory health insurance.", "تنظيم الرعاية الصحية والتأمين الصحي الإلزامي."), confirm: L("Insurance obligations and licensed providers.", "التزامات التأمين ومقدمي الخدمة المرخصين.") },
  { id: "mobility", name: L("Abu Dhabi Mobility", "أبوظبي للتنقل"), url: "https://admobility.gov.ae", why: L("Public transport, parking, tolls and driving services.", "النقل العام والمواقف والتعرفة المرورية وخدمات القيادة."), confirm: L("Bus routes, Darb toll and parking near your home.", "خطوط الحافلات ونظام درب والمواقف قرب منزلك.") },
  { id: "police", name: L("Abu Dhabi Police", "شرطة أبوظبي"), url: "https://www.adpolice.gov.ae", why: L("Driving licences, vehicle services and safety.", "رخص القيادة وخدمات المركبات والسلامة."), confirm: L("Licence conversion eligibility for your home country.", "أهلية تحويل رخصة القيادة من بلدك.") },
  { id: "fta", name: L("Federal Tax Authority", "الهيئة الاتحادية للضرائب"), url: "https://tax.gov.ae", why: L("VAT and corporate tax registration and obligations.", "تسجيل والتزامات ضريبة القيمة المضافة وضريبة الشركات."), confirm: L("Registration thresholds and filing timelines.", "حدود التسجيل ومواعيد الإقرارات.") },
  { id: "doe", name: L("Department of Energy", "دائرة الطاقة"), url: "https://www.doe.gov.ae", why: L("Regulates utilities such as electricity and water.", "تنظم المرافق مثل الكهرباء والمياه."), confirm: L("Utility connection steps for your home or office.", "خطوات توصيل المرافق لمنزلك أو مكتبك.") },
];

export const getSource = (id: string) => OFFICIAL_SOURCES.find((s) => s.id === id);

export type PrivateGroup = { key: string; title: LText; items: Array<{ name: LText; url?: string }>; kind: "commercial" | "community" };

export const PRIVATE_SERVICES: PrivateGroup[] = [
  { key: "housing", kind: "commercial", title: L("Housing", "السكن"), items: [{ name: L("Property Finder", "بروبرتي فايندر"), url: "https://www.propertyfinder.ae" }, { name: L("Bayut", "بيوت"), url: "https://www.bayut.com" }, { name: L("dubizzle", "دوبيزل"), url: "https://abudhabi.dubizzle.com" }] },
  { key: "jobs", kind: "commercial", title: L("Jobs", "الوظائف"), items: [{ name: L("LinkedIn", "لينكدإن"), url: "https://www.linkedin.com/jobs" }, { name: L("Indeed", "إنديد"), url: "https://ae.indeed.com" }, { name: L("Bayt", "بيت.كوم"), url: "https://www.bayt.com" }, { name: L("Naukrigulf", "نوكري جلف"), url: "https://www.naukrigulf.com" }] },
  { key: "education", kind: "commercial", title: L("Education", "التعليم"), items: [{ name: L("Schools", "المدارس") }, { name: L("Nurseries", "الحضانات") }, { name: L("Universities", "الجامعات") }, { name: L("Training", "التدريب") }] },
  { key: "health", kind: "commercial", title: L("Healthcare", "الرعاية الصحية"), items: [{ name: L("Hospitals", "المستشفيات") }, { name: L("Clinics", "العيادات") }, { name: L("Pharmacies", "الصيدليات") }, { name: L("Insurance", "التأمين") }] },
  { key: "transport", kind: "commercial", title: L("Transport", "التنقل"), items: [{ name: L("Public Transport", "النقل العام") }, { name: L("Taxi", "سيارات الأجرة") }, { name: L("Driving", "القيادة") }, { name: L("Rental", "تأجير السيارات") }, { name: L("Parking", "المواقف") }] },
  { key: "community", kind: "community", title: L("Community", "المجتمع"), items: [{ name: L("Professional groups", "المجموعات المهنية") }, { name: L("Cultural groups", "المجموعات الثقافية") }, { name: L("Networking", "التواصل المهني") }, { name: L("Volunteering", "التطوع") }, { name: L("Faith communities", "المجتمعات الدينية") }] },
  { key: "lifestyle", kind: "community", title: L("Lifestyle", "نمط الحياة"), items: [{ name: L("Parks", "الحدائق") }, { name: L("Beaches", "الشواطئ") }, { name: L("Culture", "الثقافة") }, { name: L("Shopping", "التسوق") }, { name: L("Dining", "المطاعم") }, { name: L("Fitness", "اللياقة") }, { name: L("Events", "الفعاليات") }] },
];