/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BelongRouteImport } from './routes/belong'
import { Route as BuildRouteImport } from './routes/build'
import { Route as CompanyCommandRouteImport } from './routes/company-command'
import { Route as ConnectRouteImport } from './routes/connect'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as LiveRouteImport } from './routes/live'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MoveRouteImport } from './routes/move'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as StartRouteImport } from './routes/start'
import { Route as WorkRouteImport } from './routes/work'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BelongRoute = BelongRouteImport.update({
  id: '/belong',
  path: '/belong',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildRoute = BuildRouteImport.update({
  id: '/build',
  path: '/build',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyCommandRoute = CompanyCommandRouteImport.update({
  id: '/company-command',
  path: '/company-command',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectRoute = ConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MoveRoute = MoveRouteImport.update({
  id: '/move',
  path: '/move',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const StartRoute = StartRouteImport.update({
  id: '/start',
  path: '/start',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkRoute = WorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/belong': typeof BelongRoute
  '/build': typeof BuildRoute
  '/company-command': typeof CompanyCommandRoute
  '/connect': typeof ConnectRoute
  '/dashboard': typeof DashboardRoute
  '/live': typeof LiveRoute
  '/login': typeof LoginRoute
  '/move': typeof MoveRoute
  '/signup': typeof SignupRoute
  '/start': typeof StartRoute
  '/work': typeof WorkRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/belong': typeof BelongRoute
  '/build': typeof BuildRoute
  '/company-command': typeof CompanyCommandRoute
  '/connect': typeof ConnectRoute
  '/dashboard': typeof DashboardRoute
  '/live': typeof LiveRoute
  '/login': typeof LoginRoute
  '/move': typeof MoveRoute
  '/signup': typeof SignupRoute
  '/start': typeof StartRoute
  '/work': typeof WorkRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/belong': typeof BelongRoute
  '/build': typeof BuildRoute
  '/company-command': typeof CompanyCommandRoute
  '/connect': typeof ConnectRoute
  '/dashboard': typeof DashboardRoute
  '/live': typeof LiveRoute
  '/login': typeof LoginRoute
  '/move': typeof MoveRoute
  '/signup': typeof SignupRoute
  '/start': typeof StartRoute
  '/work': typeof WorkRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/belong'
    | '/build'
    | '/company-command'
    | '/connect'
    | '/dashboard'
    | '/live'
    | '/login'
    | '/move'
    | '/signup'
    | '/start'
    | '/work'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/belong'
    | '/build'
    | '/company-command'
    | '/connect'
    | '/dashboard'
    | '/live'
    | '/login'
    | '/move'
    | '/signup'
    | '/start'
    | '/work'
  id:
    | '__root__'
    | '/'
    | '/belong'
    | '/build'
    | '/company-command'
    | '/connect'
    | '/dashboard'
    | '/live'
    | '/login'
    | '/move'
    | '/signup'
    | '/start'
    | '/work'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BelongRoute: typeof BelongRoute
  BuildRoute: typeof BuildRoute
  CompanyCommandRoute: typeof CompanyCommandRoute
  ConnectRoute: typeof ConnectRoute
  DashboardRoute: typeof DashboardRoute
  LiveRoute: typeof LiveRoute
  LoginRoute: typeof LoginRoute
  MoveRoute: typeof MoveRoute
  SignupRoute: typeof SignupRoute
  StartRoute: typeof StartRoute
  WorkRoute: typeof WorkRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/belong': {
      id: '/belong'
      path: '/belong'
      fullPath: '/belong'
      preLoaderRoute: typeof BelongRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/build': {
      id: '/build'
      path: '/build'
      fullPath: '/build'
      preLoaderRoute: typeof BuildRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company-command': {
      id: '/company-command'
      path: '/company-command'
      fullPath: '/company-command'
      preLoaderRoute: typeof CompanyCommandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect': {
      id: '/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof ConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/move': {
      id: '/move'
      path: '/move'
      fullPath: '/move'
      preLoaderRoute: typeof MoveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start': {
      id: '/start'
      path: '/start'
      fullPath: '/start'
      preLoaderRoute: typeof StartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work': {
      id: '/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof WorkRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BelongRoute: BelongRoute,
  BuildRoute: BuildRoute,
  CompanyCommandRoute: CompanyCommandRoute,
  ConnectRoute: ConnectRoute,
  DashboardRoute: DashboardRoute,
  LiveRoute: LiveRoute,
  LoginRoute: LoginRoute,
  MoveRoute: MoveRoute,
  SignupRoute: SignupRoute,
  StartRoute: StartRoute,
  WorkRoute: WorkRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}